### ISSUE TITLE
Image Reverse Gradient always 0

### ISSUE THREAD

**Issue by ChengFu0118** [PurduePAML/TrojanNN#2]
Dear Author,

Thanks for sharing us your code.

I have tried your code on the Face Recognition DNN model. However I cannot get the reversed image as the gradient is always 0. I have set the image reverse layer to fc8 and filter_shape to 0. I also started at the average image. 

Do you know what might be the possible cause?
Thanks.

**Comment by naiyeleo** [comment]
As talked about in http://caffe.berkeleyvision.org/tutorial/interfaces.html
We need to add set 'force_backward: true' in the network prototxt. Otherwise, caffe does not do the backward computation and the gradient is 0.
Thanks
